export const SET_PURPOSE = 'SET_PURPOSE';
export const SET_PURPOSELIST = 'SET_PURPOSELIST';
export const SET_TAB = 'SET_TAB';
export const ADD_BROKENWEBSITE = 'ADD_BROKENWEBSITE';
export const SET_CUSTOMCSS = 'SET_CUSTOMCSS';
export const SET_BANNERFILTERS = 'SET_BANNERFILTERS';
export const SET_DEFAULTCOOKIEPURPOSES = 'SET_DEFAULTCOOKIEPURPOSES';
export const ADD_ALLOWEDAPICALL = 'ADD_ALLOWEDAPICALL';
